### ISSUE TITLE
Compilation issue on Ubuntu 20.04

### ISSUE THREAD

**Issue by hcbnb** [tiagoshibata/meth-pills#2]
First of all thank you for sharing your work, I appreciate it!

When I tried to build the project on Ubuntu 20.04 I got the following error:
```
$ cmake ./
$ make
Consolidate compiler generated dependencies of target meth-pills
[ 33%] Building C object CMakeFiles/meth-pills.dir/pci.c.o
/home/gamer2/ws/meth-pills/pci.c: In function ‘read_at’:
/home/gamer2/ws/meth-pills/pci.c:36:67: warning: implicit declaration of function ‘strerrordesc_np’ [-Wimplicit-function-declaration]
   36 |         fprintf(stderr,"Failed to open %s\nopenat: %s", pathname, strerrordesc_np(errno));
      |                                                                   ^~~~~~~~~~~~~~~
/home/gamer2/ws/meth-pills/pci.c:36:53: warning: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Wformat=]
   36 |         fprintf(stderr,"Failed to open %s\nopenat: %s", pathname, strerrordesc_np(errno));
      |                                                    ~^             ~~~~~~~~~~~~~~~~~~~~~~
      |                                                     |             |
      |                                                     char *        int
      |                                                    %d
```
My gcc version is 9.3.0-17ubuntu1~20.04

By removing the call to `strerrordesc_np` I was able to build the project:
Change:
```
fprintf(stderr,"Failed to open %s\nopenat: %s", pathname, strerrordesc_np(errno));
```
to
```
fprintf(stderr,"Failed to open %s", pathname);
```

### Off topic:
Also I have ASUS DUAL GTX 1070 OC 8GB with GDDR5, but unfortunately setting the timings either doesn't have any impact on mining performance or crashes the miner and breaks the display after which I need to shutdown using the hardware button. 
With my card the default timings are:
> t0 = 32, t1 = 8

The only setting that didn't break the miner/display was `28,7`, but as I wrote it also didn't have any impact on the mining performance. Every other setting that I tried (and I tried many like 32,7, 30,6, 30,5, 24,6) broke the miner and the display.

**Comment by tiagoshibata** [comment]
Thanks for reporting, seems like `strerrordesc_np` was added to glibc in May 2020 (https://sourceware.org/pipermail/glibc-cvs/2020q3/070143.html), so you'd need a recent glibc. I'll change the code so `strerrordesc_np` isn't needed.
