### ISSUE TITLE
About windows version

### ISSUE THREAD

**Issue by gino-lu** [tiagoshibata/meth-pills#3]
This work is awesome, but it can't build in windows.
Do you have any plan about that?

Thank for sharing~

**Comment by tiagoshibata** [comment]
No concrete plans, and I have no experience with userspace PCI access in Windows (being able to do it without writing a kernel driver). I'm not too interested in picking it up myself, but contributions are welcome.

**Comment by leixiongbo** [comment]
No OpenCL platforms found

Error: No usable mining devices found
